### PR TITLE
Golint

### PR DESCRIPTION
**Pull request by repejota**
- Linted source code
- Fixed comments according Golang specs
- Added golint as a dependency
- Added a Make task to lint the source code during development
- Added lint task to travis to check the code

### CODE REVIEW

**Comment by repejota** [comment]
Looks like travis broke checks for something strange but it is working on my local branch.

**Comment by adriacidre** [comment]
I'll suggest to rebase this branch with master with includes your previous [pull request](https://github.com/supu-io/api/pull/7) with newer go versions, and just remove the conflictive golang version 1.1

**Comment by repejota** [comment]
Done!

**Comment by adriacidre** [comment]
ty :)

**Pull request merged**
